<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>run.ratchet</groupId>
        <artifactId>ratchet-parent</artifactId>
        <version>0.1.1-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>ratchet-tck</artifactId>
    <packaging>pom</packaging>
    <name>Ratchet :: TCK</name>
    <description>Aggregator for the Ratchet Technology Compatibility Kit modules</description>

    <modules>
        <module>util</module>
        <module>store</module>
        <module>api</module>
        <module>jakarta</module>
        <module>coordinator</module>
    </modules>
</project>
