package run.ratchet.testsuite.util;

import static org.junit.jupiter.api.Assertions.fail;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.Properties;
import java.util.TreeMap;
import java.util.logging.Logger;

/**
 * Loads, saves, and compares performance baselines per database type.
 *
 * <p>On first run (no baseline file), metrics are recorded to {@code target/perf-baselines/} for
 * the user to copy into {@code src/test/resources/perf-baselines/}. On subsequent runs, actual
 * values are compared against baselines with a configurable tolerance. Throughput metrics enforce a
 * lower bound because lower values are regressions; latency metrics enforce an upper bound because
 * higher values are regressions.
 */
public class PerformanceBaseline {

  private static final Logger log = Logger.getLogger(PerformanceBaseline.class.getName());

  private final Properties baselines;
  private final String dbType;
  private final double tolerance;
  private final Path outputDir;
  private final TreeMap<String, Double> recorded = new TreeMap<>();

  public PerformanceBaseline(String dbType, double tolerance, String baselineDir) {
    this.dbType = dbType;
    this.tolerance = tolerance;
    this.baselines = new Properties();
    this.outputDir =
        Path.of(System.getProperty("project.build.directory", "target"), "perf-baselines");

    String resourcePath = resourcePath(baselineDir, dbType);
    try (InputStream in =
        Thread.currentThread().getContextClassLoader().getResourceAsStream(resourcePath)) {
      if (in != null) {
        baselines.load(in);
        log.info("Loaded " + baselines.size() + " baseline values from " + resourcePath);
      } else {
        log.info("[BASELINE] No baseline file found at " + resourcePath + " — recording mode");
      }
    } catch (IOException e) {
      throw new UncheckedIOException("Baseline file unreadable: " + resourcePath, e);
    }
  }

  public void assertWithinTolerance(String metric, double actual) {
    assertBaseline(metric, actual, false);
  }

  public void assertLatencyWithinTolerance(String metric, double actualMs) {
    assertBaseline(metric, actualMs, true);
  }

  public void writeRecordedBaselines() {
    if (recorded.isEmpty()) {
      return;
    }

    try {
      Files.createDirectories(outputDir);
      Path outputFile = outputDir.resolve(dbType + "-baselines.properties");

      Properties output = new Properties();
      if (Files.exists(outputFile)) {
        try (InputStream existing = Files.newInputStream(outputFile)) {
          output.load(existing);
        }
      }

      recorded.forEach((k, v) -> output.setProperty(k, String.format("%.2f", v)));

      try (OutputStream out = Files.newOutputStream(outputFile)) {
        output.store(
            out, "Generated by Ratchet Performance Tests - " + dbType + " - " + Instant.now());
      }
      log.info("[BASELINE] Recorded baselines written to " + outputFile);
    } catch (IOException e) {
      log.warning("Baseline file not written: " + e.getMessage());
    }
  }

  private static String resourcePath(String baselineDir, String dbType) {
    Path path = Path.of(baselineDir, dbType + "-baselines.properties");
    String resourcePath = path.toString().replace('\\', '/');
    String testResourcesPrefix = "src/test/resources/";
    if (resourcePath.startsWith(testResourcesPrefix)) {
      return resourcePath.substring(testResourcesPrefix.length());
    }
    return resourcePath;
  }

  private void assertBaseline(String metric, double actual, boolean higherIsRegression) {
    requireFinite(metric, actual);
    recorded.put(metric, actual);

    String baselineStr = baselines.getProperty(metric);
    String unit = higherIsRegression ? " ms" : "";
    if (baselineStr == null) {
      log.info(
          String.format("[BASELINE] No baseline for %s, recording: %.2f%s", metric, actual, unit));
      return;
    }

    double baseline = Double.parseDouble(baselineStr);
    double bound = baseline * (1.0 + (higherIsRegression ? tolerance : -tolerance));
    boolean outsideTolerance = higherIsRegression ? actual > bound : actual < bound;
    if (outsideTolerance) {
      String regressionType = higherIsRegression ? "Latency" : "Performance";
      String boundName = higherIsRegression ? "upper" : "lower";
      fail(
          String.format(
              "%s regression for %s: baseline=%.2f%s, actual=%.2f%s, "
                  + "tolerance=%.0f%%, %s bound=%.2f%s",
              regressionType,
              metric,
              baseline,
              unit,
              actual,
              unit,
              tolerance * 100,
              boundName,
              bound,
              unit));
    }

    log.info(
        String.format(
            "[BASELINE] %s: actual=%.2f%s, baseline=%.2f%s (within %.0f%% tolerance)",
            metric, actual, unit, baseline, unit, tolerance * 100));
  }

  private static void requireFinite(String metric, double actual) {
    if (!Double.isFinite(actual)) {
      fail("Invalid performance value for " + metric + ": " + actual);
    }
  }
}
