spring.datasource.hikari.transaction-isolation=TRANSACTION_READ_COMMITTED
spring.datasource.hikari.data-source-properties.connectionTimeZone=UTC
spring.sql.init.platform=mysql
spring.sql.init.schema-locations=classpath:schema-mysql.sql
