BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE consumer_record (id VARCHAR2(80) PRIMARY KEY, state VARCHAR2(40))';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE consumer_uuid_record (id RAW(16) PRIMARY KEY, label VARCHAR2(80) NOT NULL, occurred_at TIMESTAMP(6) WITH TIME ZONE NOT NULL)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/
