<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>run.ratchet</groupId>
        <artifactId>ratchet-parent</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>ratchet-tck</artifactId>
    <name>Ratchet :: TCK</name>
    <description>Technology Compatibility Kit for Ratchet store implementations</description>

    <dependencies>
        <dependency>
            <groupId>run.ratchet</groupId>
            <artifactId>ratchet-api</artifactId>
        </dependency>
        <dependency>
            <groupId>run.ratchet</groupId>
            <artifactId>ratchet-store-core</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-web-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>testcontainers-jdbc</artifactId>
            <scope>compile</scope>
            <optional>true</optional>
        </dependency>
    </dependencies>
</project>
