ratchet_pg_connections:
  query: |
    SELECT
      current_database() AS datname,
      count(*)::float AS total,
      count(*) FILTER (WHERE state = 'active')::float AS active,
      count(*) FILTER (WHERE wait_event_type IS NOT NULL)::float AS waiting
    FROM pg_stat_activity
    WHERE datname = current_database()
  metrics:
    - datname:
        usage: "LABEL"
        description: "Database name"
    - total:
        usage: "GAUGE"
        description: "Total client connections to the current database"
    - active:
        usage: "GAUGE"
        description: "Active client connections to the current database"
    - waiting:
        usage: "GAUGE"
        description: "Client connections waiting on any PostgreSQL wait event"

ratchet_pg_waiting_locks:
  query: |
    SELECT
      current_database() AS datname,
      count(*)::float AS waiting
    FROM pg_locks
    WHERE NOT granted
  metrics:
    - datname:
        usage: "LABEL"
        description: "Database name"
    - waiting:
        usage: "GAUGE"
        description: "Locks waiting to be granted"
