/*
 * Copyright 2026 Ratchet Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package run.ratchet.spring.boot.autoconfigure;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.Set;
import java.util.concurrent.atomic.AtomicInteger;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.support.DefaultListableBeanFactory;
import run.ratchet.api.RatchetOptions;
import run.ratchet.spi.ClassPolicy;

class RatchetAotManifestClassPolicyTest {

  private static final String REGISTERED_JOB = "com.example.jobs.RegisteredJob";
  private static final String DELEGATE_DENIED_JOB = "org.example.jobs.DelegateDeniedJob";
  private static final String MISSING_JOB = "com.example.jobs.MissingJob";
  private static final String RESULT_TYPE = "com.example.results.JobResult";

  @Test
  void absentManifestLeavesTheDefaultClassPolicyInactive() {
    ClassPolicy policy = classPolicy(classLoaderWithoutManifest());

    assertFalse(policy instanceof AotManifestClassPolicy);
    assertTrue(policy.isAllowed(REGISTERED_JOB));
  }

  @Test
  void registeredInvocationClassesUseTheDelegateDecisionFromTheCachedManifest() {
    AtomicInteger resourceReads = new AtomicInteger();
    ClassPolicy policy =
        classPolicy(
            classLoaderWithManifest(
                "# generated by Ratchet AOT\n\n"
                    + REGISTERED_JOB
                    + "\n"
                    + DELEGATE_DENIED_JOB
                    + "\n",
                resourceReads));

    assertTrue(policy instanceof AotManifestClassPolicy);
    assertTrue(policy.isAllowed(REGISTERED_JOB));
    assertTrue(policy.isAllowed(REGISTERED_JOB));
    assertFalse(policy.isAllowed(DELEGATE_DENIED_JOB));
    assertEquals(1, resourceReads.get());
    assertTrue(
        policy.isAllowedForResultType(RESULT_TYPE),
        "result-type decisions must remain delegated to the configured policy");
  }

  @Test
  void manifestMissFailsWithRebuildGuidanceBeforeConsultingDelegate() {
    AtomicInteger delegateChecks = new AtomicInteger();
    ClassPolicy delegate =
        className -> {
          delegateChecks.incrementAndGet();
          return true;
        };
    RatchetAotManifest manifest =
        RatchetAotManifest.load(classLoaderWithManifest(REGISTERED_JOB + "\n", new AtomicInteger()))
            .orElseThrow();
    ClassPolicy policy = new AotManifestClassPolicy(delegate, manifest, Set.of("com.example.jobs"));

    SecurityException exception =
        assertThrows(SecurityException.class, () -> policy.isAllowed(MISSING_JOB));

    assertEquals(0, delegateChecks.get());
    assertTrue(exception.getMessage().contains(MISSING_JOB));
    assertTrue(exception.getMessage().contains(RatchetAotManifest.RESOURCE_PATH));
    assertTrue(exception.getMessage().contains("ratchet.class-policy.allowed-packages"));
    assertTrue(exception.getMessage().contains("com.example.jobs"));
    assertTrue(exception.getMessage().contains("rebuild"));
  }

  private static ClassPolicy classPolicy(ClassLoader classLoader) {
    DefaultListableBeanFactory beanFactory = new DefaultListableBeanFactory();
    beanFactory.setBeanClassLoader(classLoader);
    return new RatchetAutoConfiguration().classPolicy(options(), beanFactory);
  }

  private static RatchetOptions options() {
    return RatchetOptions.builder()
        .security(
            security ->
                security
                    .classPolicyAllowedPackages(Set.of("com.example.jobs"))
                    .classPolicyAllowedResultTypePackages(Set.of("com.example.results")))
        .build();
  }

  private static ClassLoader classLoaderWithoutManifest() {
    return new ClassLoader(null) {
      @Override
      public InputStream getResourceAsStream(String name) {
        return null;
      }
    };
  }

  private static ClassLoader classLoaderWithManifest(
      String manifestContents, AtomicInteger resourceReads) {
    byte[] contents = manifestContents.getBytes(StandardCharsets.UTF_8);
    return new ClassLoader(null) {
      @Override
      public InputStream getResourceAsStream(String name) {
        if (!RatchetAotManifest.RESOURCE_PATH.equals(name)) {
          return null;
        }
        resourceReads.incrementAndGet();
        return new ByteArrayInputStream(contents);
      }
    };
  }
}
