<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>run.ratchet</groupId>
    <artifactId>ratchet-spring-boot-parent</artifactId>
    <version>0.3.2-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>ratchet-spring-boot-starter-mongodb</artifactId>
  <name>Ratchet :: Spring Boot :: MongoDB Starter</name>
  <description>Dependency aggregator for Ratchet Spring Boot MongoDB applications</description>

  <properties>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
    </dependency>
    <dependency>
      <groupId>run.ratchet</groupId>
      <artifactId>ratchet-spring-boot-autoconfigure</artifactId>
    </dependency>
    <dependency>
      <groupId>run.ratchet</groupId>
      <artifactId>ratchet-spring-boot-autoconfigure-mongodb</artifactId>
    </dependency>
    <dependency>
      <groupId>run.ratchet</groupId>
      <artifactId>ratchet-store-mongodb</artifactId>
    </dependency>
    <dependency>
      <groupId>org.mongodb</groupId>
      <artifactId>mongodb-driver-sync</artifactId>
    </dependency>
    <dependency>
      <groupId>org.mongodb</groupId>
      <artifactId>mongodb-driver-core</artifactId>
      <version>${mongodb-driver.version}</version>
    </dependency>
    <dependency>
      <groupId>org.mongodb</groupId>
      <artifactId>bson</artifactId>
      <version>${mongodb-driver.version}</version>
    </dependency>
    <dependency>
      <groupId>org.mongodb</groupId>
      <artifactId>bson-record-codec</artifactId>
      <version>${mongodb-driver.version}</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.eclipse</groupId>
      <artifactId>yasson</artifactId>
      <version>3.0.4</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
</project>
