spring.main.banner-mode=off
spring.main.web-application-type=none
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
logging.level.root=WARN
ratchet.enabled=true
ratchet.class-policy.allowed-packages=run.ratchet.spring.boot.it.aotpreflight
