import type {SidebarsConfig} from '@docusaurus/types';

const config: SidebarsConfig = {
  gettingStartedSidebar: [
    'getting-started/introduction',
    'getting-started/installation',
    'getting-started/quickstart',
    'getting-started/basic-concepts',
    'getting-started/first-job',
    'getting-started/configuration',
  ],
  conceptsSidebar: [
    'concepts/overview',
    'concepts/job-lifecycle',
    'concepts/job-types',
    'concepts/scheduling',
    'concepts/execution-model',
    'concepts/error-handling',
    'concepts/retry-strategies',
    'concepts/batches',
    'concepts/workflows',
    'concepts/persistence',
    'concepts/clustering',
  ],
  apiReferenceSidebar: [
    'api-reference/overview',
    'api-reference/job-scheduler-service',
    'api-reference/job-builder',
    'api-reference/job-options',
    'api-reference/batch-builder',
    'api-reference/batch-context',
    'api-reference/job-context',
    'api-reference/job-result',
    'api-reference/annotations',
    'api-reference/event-system',
    'api-reference/functional-interfaces',
    'api-reference/workflow-condition',
    'api-reference/spi-interfaces',
  ],
  advancedSidebar: [
    'advanced/customization-platform',
    'advanced/spi-implementation',
    'advanced/circuit-breakers',
    'advanced/custom-retry-policies',
    'advanced/custom-serialization',
    'advanced/custom-logging',
    'advanced/metrics-collection',
  ],
  deploymentSidebar: [
    'deployment/overview',
    'deployment/installation',
    'deployment/configuration',
    'deployment/database-setup',
    'deployment/mysql',
    'deployment/postgresql',
    'deployment/mongodb',
    'deployment/clustering',
    'deployment/docker',
    'deployment/kubernetes',
    'deployment/cluster-configuration',
    'deployment/performance-tuning',
    'deployment/monitoring',
    'deployment/troubleshooting',
  ],
  troubleshootingSidebar: [
    'troubleshooting/overview',
    'troubleshooting/common-issues',
    'troubleshooting/debugging',
    'troubleshooting/faq',
  ],
};

export default config;
