import type {SidebarsConfig} from '@docusaurus/types';

const config: SidebarsConfig = {
  gettingStartedSidebar: [
    'getting-started/introduction',
    'getting-started/installation',
    'getting-started/quickstart',
    'getting-started/basic-concepts',
    'getting-started/first-job',
    'getting-started/configuration',
  ],
  conceptsSidebar: [
    'concepts/overview',
    'concepts/job-lifecycle',
    'concepts/job-types',
    'concepts/scheduling',
    'concepts/execution-model',
    'concepts/error-handling',
    'concepts/retry-strategies',
    'concepts/batches',
    'concepts/workflows',
    'concepts/persistence',
    'concepts/clustering',
  ],
  apiReferenceSidebar: [
    'api-reference/overview',
    'api-reference/job-scheduler-service',
    'api-reference/job-builder',
    'api-reference/job-options',
    'api-reference/batch-builder',
    'api-reference/batch-context',
    'api-reference/job-context',
    'api-reference/job-result',
    'api-reference/annotations',
    'api-reference/event-system',
    'api-reference/functional-interfaces',
    'api-reference/workflow-condition',
    'api-reference/spi-interfaces',
  ],
  advancedSidebar: [
    'advanced/customization-platform',
    'advanced/spi-implementation',
    'advanced/circuit-breakers',
    'advanced/custom-retry-policies',
    'advanced/custom-serialization',
    'advanced/custom-logging',
    'advanced/metrics-collection',
  ],
  deploymentSidebar: [
    'deployment/overview',
    'deployment/installation',
    'deployment/configuration',
    'deployment/database-setup',
    'deployment/mysql',
    'deployment/postgresql',
    'deployment/mongodb',
    'deployment/clustering',
    'deployment/docker',
    'deployment/kubernetes',
    'deployment/cluster-configuration',
    'deployment/performance-tuning',
    'deployment/monitoring',
    'deployment/troubleshooting',
  ],
  troubleshootingSidebar: [
    'troubleshooting/overview',
    'troubleshooting/common-issues',
    'troubleshooting/debugging',
    'troubleshooting/faq',
  ],
  conformanceSidebar: [
    'conformance/index',
    {
      type: 'category',
      label: 'Store Reports',
      items: [
        'conformance/mysql',
        'conformance/postgresql',
        'conformance/mongodb',
      ],
    },
    {
      type: 'category',
      label: 'API Reports',
      link: {type: 'doc', id: 'conformance/api/index'},
      items: [
        'conformance/api/wildfly-managed-mysql',
        'conformance/api/wildfly-managed-postgresql',
        'conformance/api/wildfly-managed-mongodb',
        'conformance/api/payara-managed-mysql',
        'conformance/api/payara-managed-postgresql',
        'conformance/api/payara-managed-mongodb',
        'conformance/api/openliberty-managed-mysql',
        'conformance/api/openliberty-managed-postgresql',
        'conformance/api/openliberty-managed-mongodb',
        'conformance/api/glassfish-managed-mysql',
        'conformance/api/glassfish-managed-postgresql',
        'conformance/api/glassfish-managed-mongodb',
      ],
    },
    {
      type: 'category',
      label: 'Jakarta Runtime Reports',
      link: {type: 'doc', id: 'conformance/jakarta/index'},
      items: [
        'conformance/jakarta/wildfly-managed-mysql',
        'conformance/jakarta/wildfly-managed-postgresql',
        'conformance/jakarta/wildfly-managed-mongodb',
        'conformance/jakarta/payara-managed-mysql',
        'conformance/jakarta/payara-managed-postgresql',
        'conformance/jakarta/payara-managed-mongodb',
        'conformance/jakarta/openliberty-managed-mysql',
        'conformance/jakarta/openliberty-managed-postgresql',
        'conformance/jakarta/openliberty-managed-mongodb',
        'conformance/jakarta/glassfish-managed-mysql',
        'conformance/jakarta/glassfish-managed-postgresql',
        'conformance/jakarta/glassfish-managed-mongodb',
      ],
    },
  ],
};

export default config;
